# This is a basic workflow to help you get started with Actions

name: stage & preview workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  preview:
    name: Create Preview
    runs-on: ubuntu-20.04
    environment:
      name: testpypi
      url: https://test.pypi.org/p/ds-best-practice-example/

    permissions:
      id-token: write # Required for trusted publishing on PyPI

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install poetry tox tox-gh-actions

      - name: Setup doc deploy git user # required for mike
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Test with tox
        run: tox

      - name: Build wheels and source tarball
        run: |
          poetry version $(poetry version --short)-dev.$GITHUB_RUN_NUMBER
          poetry version --short
          poetry build

      - name: Show temporary files
        run: ls -l .

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
