# Publish package on main branch if it's tagged with 'v*'

name: release & publish workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "release"
  release:
    name: Create Release
    runs-on: ubuntu-20.04
    environment:
      name: pypi
      url: https://pypi.org/p/ds-best-practice-example/

    permissions:
      id-token: write # Required for trusted publishing on PyPI
      contents: write # Required for action-gh-release

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get Changelog entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: warn
          path: ./CHANGELOG.md

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install poetry

      - name: Setup doc deploy git user # required for mike
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Build documentation
        run: |
          poetry install -E doc
          git fetch origin gh-pages --depth=1
          poetry run mike deploy --push --update-aliases ${{ steps.changelog_reader.outputs.version }} latest
          poetry run mike set-default --push latest

      - name: Build wheels and source tarball
        run: poetry build

      - name: Show temporary files
        run: ls -l .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog_reader.outputs.changes }}
          files: dist/*.whl
          draft: false
          prerelease: false

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
